// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TypeRunnerBE.Models;

#nullable disable

namespace TypeRunnerBE.Migrations
{
    [DbContext(typeof(TypeMarathonContext))]
    [Migration("20230303182111_AddRaceAndQuote")]
    partial class AddRaceAndQuote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TypeMarathonBE.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageWpm")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentRaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRaceId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.UserFriend", b =>
                {
                    b.Property<int>("FromUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ToUserId")
                        .HasColumnType("integer");

                    b.HasKey("FromUserId", "ToUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("UserFriends", (string)null);
                });

            modelBuilder.Entity("TypeMarathonBE.Models.UserRaceMistake", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Word")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RaceId", "Word");

                    b.ToTable("UserRaceMistake");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.UserRaceRecord", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("Wpm")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("UserRaceRecords");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.Quote", b =>
                {
                    b.HasOne("TypeMarathonBE.Models.Author", "Author")
                        .WithMany("Quotes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.Race", b =>
                {
                    b.HasOne("TypeMarathonBE.Models.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.User", b =>
                {
                    b.HasOne("TypeMarathonBE.Models.Race", "CurrentRace")
                        .WithMany("Racers")
                        .HasForeignKey("CurrentRaceId");

                    b.Navigation("CurrentRace");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.UserFriend", b =>
                {
                    b.HasOne("TypeMarathonBE.Models.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TypeMarathonBE.Models.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.UserRaceMistake", b =>
                {
                    b.HasOne("TypeMarathonBE.Models.UserRaceRecord", "UserRace")
                        .WithMany("Mistakes")
                        .HasForeignKey("UserId", "RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRace");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.UserRaceRecord", b =>
                {
                    b.HasOne("TypeMarathonBE.Models.Race", "Race")
                        .WithMany("UserRecords")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TypeMarathonBE.Models.User", "User")
                        .WithMany("RaceRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.Author", b =>
                {
                    b.Navigation("Quotes");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.Race", b =>
                {
                    b.Navigation("Racers");

                    b.Navigation("UserRecords");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.User", b =>
                {
                    b.Navigation("RaceRecords");
                });

            modelBuilder.Entity("TypeMarathonBE.Models.UserRaceRecord", b =>
                {
                    b.Navigation("Mistakes");
                });
#pragma warning restore 612, 618
        }
    }
}
